import { describe, it, expect } from 'vitest';
import { generateGame } from '../../src/world/generate.ts';
import { tick } from '../../src/sim/tick.ts';
import { productionSystem, OUTPUT_CAP } from '../../src/sim/systems/production.ts';
import { demandSystem, MAX_BACKLOG_DAYS } from '../../src/sim/systems/demand.ts';
import { makeIndustry } from '../../src/sim/model/industries.ts';
import { makeCity } from '../../src/sim/model/cities.ts';
import { createGameState } from '../../src/sim/state.ts';

describe('production', () => {
  it('raw extractors accumulate output up to the cap', () => {
    const s = createGameState(1);
    s.industries.push(makeIndustry('m', 'coalMine', 0, 0));
    for (let i = 0; i < 100; i++) tick(s, 1, [productionSystem]);
    expect(s.industries[0].outputStock).toBeGreaterThan(0);
    expect(s.industries[0].outputStock).toBeLessThanOrEqual(OUTPUT_CAP);
  });

  it('a processor only yields output when its inputs are present', () => {
    const s = createGameState(1);
    const mill = makeIndustry('mill', 'steelMill', 0, 0); // needs iron + coal
    s.industries.push(mill);

    // No inputs -> no steel, however long it runs.
    for (let i = 0; i < 20; i++) tick(s, 1, [productionSystem]);
    expect(mill.outputStock).toBe(0);

    // Supply inputs -> steel is produced (multi-stage chain, R9).
    mill.inputStock = { iron: 20, coal: 20 };
    for (let i = 0; i < 20; i++) tick(s, 1, [productionSystem]);
    expect(mill.outputStock).toBeGreaterThan(0);
    expect(mill.inputStock.iron!).toBeLessThan(20);
  });
});

describe('demand', () => {
  it('city backlog grows toward a per-day cap when unfed', () => {
    const s = createGameState(1);
    const city = makeCity('c', 'Testville', 0, 0, 0);
    s.cities.push(city);
    tick(s, 1, [demandSystem]);
    const afterOne = city.backlog.food!;
    for (let i = 0; i < 100; i++) tick(s, 1, [demandSystem]);
    const capped = city.backlog.food!;
    expect(afterOne).toBeGreaterThan(0);
    expect(capped).toBeLessThanOrEqual(city.demand.food! * MAX_BACKLOG_DAYS + 1e-9);
    expect(capped).toBeGreaterThan(afterOne);
  });

  it('passenger and mail demand is generated by population', () => {
    const city = makeCity('c', 'Testville', 0, 0, 0);
    expect(city.demand.passengers).toBeGreaterThan(0);
    expect(city.demand.mail).toBeGreaterThan(0);
  });

  it('the full world economy evolves with no trains running', () => {
    const s = generateGame(4);
    tick(s); // default pipeline: production + demand
    for (let i = 0; i < 50; i++) tick(s);
    const anyStock = s.industries.some((i) => i.outputStock > 0);
    const anyBacklog = s.cities.some((c) => Object.values(c.backlog).some((v) => (v ?? 0) > 0));
    expect(anyStock).toBe(true);
    expect(anyBacklog).toBe(true);
  });
});
